#!/usr/bin/env python3

"""
Git hook to automatically prefix a git commit message with an issue number
(e.g. Jira ticket number) from the current branch name.
"""

import re
import sys
from subprocess import check_output


def main():
    commit_msg_filepath = sys.argv[1]
    branch = (
        check_output(["git", "symbolic-ref", "--short", "HEAD"]).decode("utf-8").strip()
    )
    regex_jira_id = r"^(\w+-\d+)"

    branch_match = re.match(regex_jira_id, branch)
    if not branch_match:
        return

    issue_number = branch_match.group(1)
    with open(commit_msg_filepath, "r+") as f:
        commit_msg = f.read()
        f.seek(0, 0)  # correctly positions issue_number when writing commit message
        f.write(f"[{issue_number}] {commit_msg}")


if __name__ == "__main__":
    main()
